module.exports = {
  Surah: [
    { name: "1.  Al Fatihah (Pembuka)", value: 1 },
    { name: "2.  Al Baqarah (Sapi Betina)", value: 2 },
    { name: "3.  Ali Imran (Keluarga Imran)", value: 3 },
    { name: "4.  An Nisa (Wanita)", value: 4 },
    { name: "5.  Al Ma'idah (Jamuan)", value: 5 },
    { name: "6.  Al An'am (Hewan Ternak)", value: 6 },
    { name: "7.  Al-A'raf (Tempat yang Tertinggi)", value: 7 },
    { name: "8.  Al-Anfal (Harta Rampasan Perang)", value: 8 },
    { name: "9.  At-Taubah(Pengampunan)", value: 9 },
    { name: "10. Yunus (Nabi Yunus)", value: 10 },
    { name: "11. Hud (Nabi Hud)", value: 11 },
    { name: "12. Yusuf (Nabi Yusu)", value: 12 },
    { name: "13. Ar-Ra'd (Guruh)", value: 13 },
    { name: "14. Ibrahim (Nabi Ibrahim)", value: 14 },
    { name: "15. Al-Hijr (Gunung Al Hijr)", value: 15 },
    { name: "16. An-Nahl (Lebah)", value: 16 },
    { name: "17. Al-Isra' (Perjalanan Malam)", value: 17 },
    { name: "18. Al-Kahf (Penghuni-penghuni Gua)", value: 18 },
    { name: "19. Maryam (Maryam)", value: 19 },
    { name: "20. Ta Ha (Ta Ha)", value: 20 },
    { name: "21. Al-Anbiya (Nabi-Nabi)", value: 21 },
    { name: "22. Al-Hajj (Haji)", value: 22 },
    { name: "23. Al-Mu'minun (Orang-orang mukmin)", value: 23 },
    { name: "24. An-Nur (Cahaya)", value: 24 },
    { name: "25. Al-Furqan (Pembeda)", value: 25 },
    { name: "26. Asy-Syu'ara' (Penyair)", value: 26 },
    { name: "27. An-Naml (Semut)", value: 27 },
    { name: "28. Al-Qasas (Kisah-kisah)", value: 28 },
    { name: "29. Al-'Ankabut (Laba-laba)", value: 29 },
    { name: "30. Ar-Rum (Bangsa Romawi)", value: 30 },
    { name: "31. Luqman (Keluarga Luqman)", value: 31 },
    { name: "32. As-Sajdah (Sajdah)", value: 32 },
    { name: "33. Al-Ahzab (Golongan-golongan yang Bersekutu)", value: 33 },
    { name: "34. Saba' (Kaum Saba')", value: 34 },
    { name: "35. Fatir (Pencipta)", value: 35 },
    { name: "36. Ya Sin (Yaasiin)", value: 36 },
    { name: "37. As-Saffat (Barisan-barisan)", value: 37 },
    { name: "38. Sad (Shaad)", value: 38 },
    { name: "39. Az-Zumar (Rombongan-rombongan)", value: 39 },
    { name: "40. Ghafir (Yang Mengampuni)", value: 40 },
    { name: "41. Fussilat (Yang Dijelaskan)", value: 41 },
    { name: "42. Asy-Syura (Musyawarah)", value: 42 },
    { name: "43. Az-Zukhruf (Perhiasan)", value: 43 },
    { name: "44. Ad-Dukhan (Kabut)", value: 44 },
    { name: "45. Al-Jasiyah (Yang Bertekuk Lutut)", value: 45 },
    { name: "46. Al-Ahqaf (Bukit-bukit Pasir)", value: 46 },
    { name: "47. Muhammad (Nabi Muhammad)", value: 47 },
    { name: "48. Al-Fath (Kemenangan)", value: 48 },
    { name: "49. Al-Hujurat (Kamar-kamar)", value: 49 },
    { name: "50. Qaf (Qaaf)", value: 50 },
    { name: "51. Az-Zariyat (Angin yang Menerbangkan)", value: 51 },
    { name: "52. At-Tur (Bukit)", value: 52 },
    { name: "53. An-Najm (Bintang)", value: 53 },
    { name: "54. Al-Qamar (Bulan)", value: 54 },
    { name: "55. Ar-Rahman (Yang Maha Pemurah)", value: 55 },
    { name: "56. Al-Waqi'ah (Hari Kiamat)", value: 56 },
    { name: "57. Al-Hadid (Besi)", value: 57 },
    { name: "58. Al-Mujadilah (Wanita yang Mengajukan Gugatan)", value: 58 },
    { name: "59. Al-Hasyr (Pengusiran)", value: 59 },
    { name: "60. Al-Mumtahanah (Wanita yang Diuji)", value: 60 },
    { name: "61. As-Saff (Satu Barisan)", value: 61 },
    { name: "62. Al-Jumu'ah (Hari Jum'at)", value: 62 },
    { name: "63. Al-Munafiqun (Orang-orang yang Munafik)", value: 63 },
    {
      name: "64. At-Tagabun (Hari Dinampakkan Kesalahan-kesalahan)",
      value: 64,
    },
    { name: "65. At-Talaq (Talak)", value: 65 },
    { name: "67. Al-Mulk (Kerajaan)", value: 67 },
    { name: "68. Al-Qalam (Pena)", value: 68 },
    { name: "69. Al-Haqqah (Hari Kiamat)", value: 69 },
    { name: "70. Al-Ma'arij (Tempat Naik)", value: 70 },
    { name: "71. Nuh (Nabi Nuh)", value: 71 },
    { name: "72. Al-Jinn (Jin)", value: 72 },
    { name: "73. Al-Muzzammil (Orang yang Berselimut)", value: 73 },
    { name: "74. Al-Muddassir (Orang yang Berkemul)", value: 74 },
    { name: "75. Al-Qiyamah (Kiamat)", value: 75 },
    { name: "76. Al-Insan (Manusia)", value: 76 },
    { name: "77. Al-Mursalat (Malaikat-Malaikat Yang Diutus)", value: 77 },
    { name: "78. An-Naba' (Berita Besar)", value: 78 },
    { name: "79. An-Nazi'at (Malaikat-Malaikat Yang Mencabut)", value: 79 },
    { name: "80. 'Abasa (Ia Bermuka Masam)", value: 80 },
    { name: "81. At-Takwir (Menggulung)", value: 81 },
    { name: "82. Al-Infitar (Terbelah)", value: 82 },
    { name: "83. Al-Tatfif (Orang-orang yang Curang)", value: 83 },
    { name: "84. Al-Insyiqaq (Terbelah)", value: 84 },
    { name: "85. Al-Buruj (Gugusan Bintang)", value: 85 },
    { name: "86. At-Tariq (Yang Datang di Malam Hari)", value: 86 },
    { name: "87. Al-A'la (Yang Paling Tinggi)", value: 87 },
    { name: "88. Al-Gasyiyah (Hari Pembalasan)", value: 88 },
    { name: "89. Al-Fajr (Fajar)", value: 89 },
    { name: "90. Al-Balad (Negeri)", value: 90 },
    { name: "91. Asy-Syams (Matahari)", value: 91 },
    { name: "92. Al-Lail (Malam)", value: 92 },
    {
      name: "93. Ad-Duha (Waktu Matahari Sepenggalahan Naik (Dhuha))",
      value: 93,
    },
    { name: "94. Al-Insyirah (Melapangkan)", value: 94 },
    { name: "95. At-Tin (Buah Tin)", value: 95 },
    { name: "96. Al-'Alaq (Segumpal Darah)", value: 96 },
    { name: "97. Al-Qadr (Kemuliaan)", value: 97 },
    { name: "98. Al-Bayyinah (Pembuktian)", value: 98 },
    { name: "99. Az-Zalzalah (Kegoncangan)", value: 99 },
    { name: "100. Al-'Adiyat (Berlari Kencang)", value: 100 },
    { name: "101. Al-Qari'ah (Hari Kiamat)", value: 101 },
    { name: "102. At-Takasur (Bermegah-megahan)", value: 102 },
    { name: "103. Al-'Asr (Masa)", value: 103 },
    { name: "104. Al-Humazah (Pengumpat)", value: 104 },
    { name: "105. Al-Fil (Gajah)", value: 105 },
    { name: "106. Quraisy (Suku Quraisy)", value: 106 },
    { name: "107. Al-Ma'un (Barang-barang yang Berguna)", value: 107 },
    { name: "108. Al-Kausar (Nikmat yang Berlimpah)", value: 108 },
    { name: "109. Al-Kafirun (Orang-orang Kafir)", value: 109 },
    { name: "110. An-Nasr (Pertolongan)", value: 110 },
    { name: "111. Al-Lahab (Gejolak Api)", value: 111 },
    { name: "112. Al-Ikhlas (Ikhlas)", value: 112 },
    { name: "113. Al-Falaq (Waktu Subuh)", value: 113 },
    { name: "114. An-Nas (Umat Manusia)", value: 114 },
  ],
};
